services:
  - type: web
    name: resume-screener-api
    env: python
    plan: free
    region: ohio
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: GEMINI_API_KEY
        sync: false
